### ISSUE TITLE
Try-It code lens does not work with "Fast Run"

### ISSUE THREAD

**Issue by hasithaa** [wso2/ballerina-vscode#503] opened 2023-06-15 08:29 UTC
See attached video. Observed with Update 6 GA. 

https://github.com/wso2/ballerina-plugin-vscode/assets/1356214/9f657c92-9159-4ab6-b41d-9f59f65c48f2

Issues. 
- `tryit` disappear when clicking on run.
- Had to reopen the file to click `tryit`
- You can't stop running the service after closing the file (had to close it manually using `kill -9`)

**Comment by gigara** [comment] 2023-06-19 06:08
Fixed in v4.3.0

**Comment by manuranga** [comment] 2023-06-20 11:28
This has has multiple issues. Only 1 is fixed. Reopening.

**Comment by manuranga** [comment] 2023-06-21 11:29
For 3:
I was able to fix by changing
```diff
diff --git a/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java b/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
--- a/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java	(revision e36fc7ac74a7b5aea2a9cabea6162bd1560a0a9a)
+++ b/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java	(date 1687329218991)
@@ -734,7 +734,7 @@
         methods.add(owner.initializerFunc);
 
         for (BAttachedFunction mthd : methods) {
-            if (method == mthd.symbol) {
+            if (mthd != null && method.getName().equals(mthd.symbol.getName())) {
                 if (mthd instanceof BResourceFunction) {
                     return ((BResourceFunction) mthd).accessor.value;
                 }
```
But this is not the file fix. The root cause is `BObjectTypeSymbol.initializerFunc` being `null`.

**Comment by manuranga** [comment] 2023-11-17 08:45
> But this is not the file fix. The root cause is BObjectTypeSymbol.initializerFunc being null.
This is wrong, actually this is a per-exisitng logical bug in this code. But since `null` is always the last element, we never get the NPE.

Real issue is after codegen, symbols are different so we don't get `method == mthd.symbol` even when it should. So we reach the end of the list, exposing already existing `null`.

**Closed** 2024-03-28 07:06 UTC
Labels: Type/Bug, Resolution/Fixed
